[general]
port=80
compression = true



#### CORS
cors-allow-origins = ""
cors-allow-headers = ""


[advanced]

[[advanced.headers]]
source = "**/*.{wasm}"
headers = { Content-Type = "application/wasm" }